### ISSUE TITLE
File upload abort crashes server

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/adonis-middleware#9]
_From @exhovo on March 21, 2017 7:8_

Hi
We are using [fineuploader](https://fineuploader.com/) which has cancel button during upload. If we press on cancel we got error at node js 

> ...project-path/node_modules/adonis-middleware/src/BodyParser/index.js:111
        throw error
        ^
Error: Request aborted
    at IncomingMessage.<anonymous> (...project-path/node_modules/formidable/lib/incoming_form.js:120:19)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at abortIncoming (_http_server.js:284:11)
    at TLSSocket.serverSocketCloseListener (_http_server.js:297:5)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at _handle.close (net.js:501:12)
    at Socket.done (_tls_wrap.js:325:7)
    at Socket.g (events.js:292:16)

After investigations we founded out that it is thrown from this code block 

    form.on('error', function (error) {
        throw error
     })

**Can we somehow handle this error or is there another solution to not crash server on upload abort.**
It even crashes when during upload we refresh the page.

Thanks, Hovo.

_Copied from original issue: adonisjs/adonis-framework#520_

**Comment by thetutlage** [comment]
You can catch exceptions inside the global `Http error handler`. http://adonisjs.com/docs/3.2/error-and-exceptions#_catching_exception

**Comment by thetutlage** [comment]
_From @exhovo on March 21, 2017 7:24_

I have tried but it's not working. And error which has been thrown is not an object it's just message.

**Comment by thetutlage** [comment]
Okay, lemme look into so that it bubbles up to the exception handler.

**Comment by thetutlage** [comment]
_From @exhovo on March 21, 2017 8:18_

I have tested with simple html form uploaded large file and during upload refreshed browser and got the same error.

    <form method="post" enctype="multipart/form-data" action="https://domain.com:3004/file-uploader/common/">
        <input type="file" name="upload_file">
        <button type="submit">upload</button>
    </form>

**Comment by thetutlage** [comment]
_From @exhovo on March 21, 2017 9:42_

Only solution which I found is duplicate adonis-middleware/src/BodyParser/index.js with changing 

    form.on('error', function (error) {
    throw error
    })

TO

    class RequestAborted extends NE.LogicalException {}
    ......
    form.on('aborted', function () {
        form._error(new RequestAborted('Aborted error', 413))
        return
    })

    form.on('error', function (error) {
        if(error.name !== 'RequestAborted') {
            throw error
        }
    })

**Comment by thetutlage** [comment]
_From @zztv1 on March 27, 2017 7:23_

Got the same issue today.
